events {
}
http {
    server {
        listen 443 ssl;
        server_name kait-baa.43.fr;

        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        # WordPress files will be here
        root /var/www/html;
        index index.php index.html;

        # PHP configuration
        # For any request ending in .php, send it to the PHP handler (PHP-FPM)
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # respose 404 error for all other requests if not found
        # error_page 404 /404.html;
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
